# Generated by Django 3.2.4 on 2021-07-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_junior', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
